In [2]:
import numpy as np

In [3]:
from numpy import genfromtxt

In [4]:
fpath = ("tipsf.csv")

In [5]:
x= np.genfromtxt(fpath,delimiter =',', skip_header=True)
print(x)

[[  0.    16.99   1.01 ...   1.     0.     2.  ]
 [  1.    10.34   1.66 ...   1.     0.     3.  ]
 [  2.    21.01   3.5  ...   1.     0.     3.  ]
 ...
 [241.    22.67   2.   ...   0.     0.     2.  ]
 [242.    17.82   1.75 ...   0.     0.     2.  ]
 [243.    18.78   3.   ...   2.     0.     2.  ]]

In [6]:
np.sum(x[:,1])#total bill value

4827.77

In [7]:
np.sum(x[:,2])#total tip value

731.5799999999999

In [8]:
x[:,2]

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,  2.  ,  2.18,  1.5 ,  2.83,  1.5 ,  2.  ,  3.25,
        1.25,  2.  ,  2.  ,  2.  ,  2.75,  3.5 ,  6.7 ,  5.  ,  5.  ,
        2.3 ,  1.5 ,  1.36,  1.63,  1.73,  2.  ,  2.5 ,  2.  ,  2.74,
        2.  ,  2.  ,  5.14,  5.  ,  3.75,  2.61,  2.  ,  3.5 ,  2.5 ,
        2.  ,  2.  ,  3.  ,  3.48,  2.24,  4.5 ,  1.61,  2.  , 10.  ,
        3.16,  5.15,  3.18,  4.  ,  3.11,  2.  ,  2.  ,  4.  ,  3.55,
        3.68,  5.65,  3.5 ,  6.5 ,  3.  ,  5.  ,  3.5 ,  2.  ,  3.5 ,
        4.  ,  1.5 ,  4.19,  2.56,  2.02,  4.  ,  1.44,  2.  ,  5.  ,
        2.  ,  2.  ,  4.  ,  2.01,  2.  ,  2.5 ,  4.  ,  3.23,  3.41,
        3.  ,  2.03,  2.23,  2.  ,  5.16,  9.  ,  2.5 ,  6.5 ,  1.1 ,
        3.  ,  1.5 ,  1.44,  3.09,  2.2 ,  3.48,  1.92,  3.  ,  1.58,
        2.5 ,  2.  ,  3.  ,  2.72,  2.88,  2.  ,  3.  ,  3.39,  1.47,
        3.  ,  1.25,  1.  ,  1.17,  4.67,  5.92,  2.  ,  2.  ,  1.75,
        3.  ])

In [9]:
np.unique(x,return_index = True,return_counts = True)

(array([  0.  ,   1.  ,   1.01,   1.1 ,   1.17,   1.25,   1.32,   1.36,
          1.44,   1.45,   1.47,   1.48,   1.5 ,   1.56,   1.57,   1.58,
          1.61,   1.63,   1.64,   1.66,   1.67,   1.68,   1.71,   1.73,
          1.75,   1.76,   1.8 ,   1.83,   1.92,   1.96,   1.97,   1.98,
          2.  ,   2.01,   2.02,   2.03,   2.05,   2.09,   2.18,   2.2 ,
          2.23,   2.24,   2.3 ,   2.31,   2.34,   2.45,   2.47,   2.5 ,
          2.52,   2.54,   2.55,   2.56,   2.6 ,   2.61,   2.64,   2.71,
          2.72,   2.74,   2.75,   2.83,   2.88,   2.92,   3.  ,   3.02,
          3.06,   3.07,   3.08,   3.09,   3.11,   3.12,   3.14,   3.15,
          3.16,   3.18,   3.21,   3.23,   3.25,   3.27,   3.31,   3.35,
          3.39,   3.4 ,   3.41,   3.48,   3.5 ,   3.51,   3.55,   3.6 ,
          3.61,   3.68,   3.71,   3.75,   3.76,   3.92,   4.  ,   4.06,
          4.08,   4.19,   4.2 ,   4.29,   4.3 ,   4.34,   4.5 ,   4.67,
          4.71,   4.73,   5.  ,   5.07,   5.14,   5.15,   5.16,   5.17,
          5.2 ,   5.6 ,   5.65,   5.75,   5.85,   5.92,   6.  ,   6.5 ,
          6.7 ,   6.73,   7.  ,   7.25,   7.51,   7.56,   7.58,   7.74,
          8.  ,   8.35,   8.51,   8.52,   8.58,   8.77,   9.  ,   9.55,
          9.6 ,   9.68,   9.78,   9.94,  10.  ,  10.07,  10.09,  10.27,
         10.29,  10.33,  10.34,  10.51,  10.59,  10.63,  10.65,  10.77,
         11.  ,  11.02,  11.17,  11.24,  11.35,  11.38,  11.59,  11.61,
         11.69,  11.87,  12.  ,  12.02,  12.03,  12.16,  12.26,  12.43,
         12.46,  12.48,  12.54,  12.6 ,  12.66,  12.69,  12.74,  12.76,
         12.9 ,  13.  ,  13.03,  13.13,  13.16,  13.27,  13.28,  13.37,
         13.39,  13.42,  13.51,  13.81,  13.94,  14.  ,  14.07,  14.15,
         14.26,  14.31,  14.48,  14.52,  14.73,  14.78,  14.83,  15.  ,
         15.01,  15.04,  15.06,  15.36,  15.38,  15.42,  15.48,  15.53,
         15.69,  15.77,  15.81,  15.95,  15.98,  16.  ,  16.04,  16.21,
         16.27,  16.29,  16.31,  16.32,  16.4 ,  16.43,  16.45,  16.47,
         16.49,  16.58,  16.66,  16.82,  16.93,  16.97,  16.99,  17.  ,
         17.07,  17.26,  17.29,  17.31,  17.46,  17.47,  17.51,  17.59,
         17.78,  17.81,  17.82,  17.89,  17.92,  18.  ,  18.04,  18.15,
         18.24,  18.26,  18.28,  18.29,  18.35,  18.43,  18.64,  18.69,
         18.71,  18.78,  19.  ,  19.08,  19.44,  19.49,  19.65,  19.77,
         19.81,  19.82,  20.  ,  20.08,  20.23,  20.27,  20.29,  20.45,
         20.49,  20.53,  20.65,  20.69,  20.76,  20.9 ,  20.92,  21.  ,
         21.01,  21.16,  21.5 ,  21.58,  21.7 ,  22.  ,  22.12,  22.23,
         22.42,  22.49,  22.67,  22.75,  22.76,  22.82,  23.  ,  23.1 ,
         23.17,  23.33,  23.68,  23.95,  24.  ,  24.01,  24.06,  24.08,
         24.27,  24.52,  24.55,  24.59,  24.71,  25.  ,  25.21,  25.28,
         25.29,  25.56,  25.71,  25.89,  26.  ,  26.41,  26.59,  26.86,
         26.88,  27.  ,  27.05,  27.18,  27.2 ,  27.28,  28.  ,  28.15,
         28.17,  28.44,  28.55,  28.97,  29.  ,  29.03,  29.8 ,  29.85,
         29.93,  30.  ,  30.06,  30.14,  30.4 ,  30.46,  31.  ,  31.27,
         31.71,  31.85,  32.  ,  32.4 ,  32.68,  32.83,  32.9 ,  33.  ,
         34.  ,  34.3 ,  34.63,  34.65,  34.81,  34.83,  35.  ,  35.26,
         35.83,  36.  ,  37.  ,  38.  ,  38.01,  38.07,  38.73,  39.  ,
         39.42,  40.  ,  40.17,  40.55,  41.  ,  41.19,  42.  ,  43.  ,
         43.11,  44.  ,  44.3 ,  45.  ,  45.35,  46.  ,  47.  ,  48.  ,
         48.17,  48.27,  48.33,  49.  ,  50.  ,  50.81,  51.  ,  52.  ,
         53.  ,  54.  ,  55.  ,  56.  ,  57.  ,  58.  ,  59.  ,  60.  ,
         61.  ,  62.  ,  63.  ,  64.  ,  65.  ,  66.  ,  67.  ,  68.  ,
         69.  ,  70.  ,  71.  ,  72.  ,  73.  ,  74.  ,  75.  ,  76.  ,
         77.  ,  78.  ,  79.  ,  80.  ,  81.  ,  82.  ,  83.  ,  84.  ,
         85.  ,  86.  ,  87.  ,  88.  ,  89.  ,  90.  ,  91.  ,  92.  ,
         93.  ,  94.  ,  95.  ,  96.  ,  97.  ,  98.  ,  99.  , 100.  ,
        101.  , 102.  , 103.  , 104.  , 105.  , 106.  , 107.  , 108.  ,
        109.  , 110.  , 111.  , 112.  , 113.  , 114.  , 115.  , 116.  ,
        117.  , 118.  , 119.  , 120.  , 121.  , 122.  , 123.  , 124.  ,
        125.  , 126.  , 127.  , 128.  , 129.  , 130.  , 131.  , 132.  ,
        133.  , 134.  , 135.  , 136.  , 137.  , 138.  , 139.  , 140.  ,
        141.  , 142.  , 143.  , 144.  , 145.  , 146.  , 147.  , 148.  ,
        149.  , 150.  , 151.  , 152.  , 153.  , 154.  , 155.  , 156.  ,
        157.  , 158.  , 159.  , 160.  , 161.  , 162.  , 163.  , 164.  ,
        165.  , 166.  , 167.  , 168.  , 169.  , 170.  , 171.  , 172.  ,
        173.  , 174.  , 175.  , 176.  , 177.  , 178.  , 179.  , 180.  ,
        181.  , 182.  , 183.  , 184.  , 185.  , 186.  , 187.  , 188.  ,
        189.  , 190.  , 191.  , 192.  , 193.  , 194.  , 195.  , 196.  ,
        197.  , 198.  , 199.  , 200.  , 201.  , 202.  , 203.  , 204.  ,
        205.  , 206.  , 207.  , 208.  , 209.  , 210.  , 211.  , 212.  ,
        213.  , 214.  , 215.  , 216.  , 217.  , 218.  , 219.  , 220.  ,
        221.  , 222.  , 223.  , 224.  , 225.  , 226.  , 227.  , 228.  ,
        229.  , 230.  , 231.  , 232.  , 233.  , 234.  , 235.  , 236.  ,
        237.  , 238.  , 239.  , 240.  , 241.  , 242.  , 243.  ]),
 array([   0,    5,    2, 1722, 1898,  602,  346, 1170, 1562,  242, 1866,
        1010,  458,  426,   98, 1794, 1346, 1178,  842,   10,  130,  970,
          82, 1186, 1938,  466,  946,  658, 1778,   66,  562,  498,    7,
         546, 1546,  674,  386,  554, 1034,  594,  178,  322, 1154,  306,
         202,  266,  530,  250,  994,  330,  906, 1538,  410, 1266,  514,
         634, 1826, 1218,  170, 1050, 1834,  954,   15,  114,  338,  298,
         610, 1754, 1402,   58,  578,  522, 1370,  194,  482,   74,  754,
         274,   26,  154, 1858,  650, 1650,  826,   18,  442, 1434,  282,
          34, 1442,  138, 1258,  506,  122,   32,  850,  162, 1530, 1002,
         858,  226,  434, 1338, 1906,   42,  762,   40,  930, 1242, 1378,
        1690,  682,  418,  354, 1450,  737,  706, 1914,   48, 1466, 1130,
         474,   56,  889, 1193, 1561,  186, 1745,   64, 1161, 1081, 1009,
        1777,   49,   72,  241, 1425,  345, 1185,  425,   80,  657, 1809,
          81,  409,  129,    9,  601, 1345, 1353,  937, 1865,   88,  497,
        1057,  465,  801, 1025, 1737, 1857,  961, 1177,   96,  561,  777,
        1761, 1065,  945,  793,  993,  401, 1889, 1289,  217, 1609, 1673,
        1721,  104,  689, 1209, 1113, 1705, 1825,  209, 1265,  969, 1593,
         489,  337,  112, 1201, 1097,  977,  873, 1417, 1017,  593,   73,
         113,  120,  553,   65,  257,  841,  809,   97, 1545, 1873, 1521,
         177, 1369,  985,  673,  128,  321, 1297, 1801,  137,  289,  745,
        1625, 1153,  529, 1641, 1273, 1553,  649, 1393,  297,  145,    1,
         136,  569, 1217,  633,  921,  329, 1121, 1313,  513,  273,  201,
        1937, 1409,  161,  144,  393, 1505,  865, 1073,  697,  361,  249,
         105, 1169,  305, 1601, 1945,  152, 1041,  641,  441,  233, 1233,
        1529,  193,  160,  521,  545, 1049,  169, 1817,  849, 1633,  153,
         265, 1329, 1489,  833,  168,   17,  713, 1281,  121,  225,  176,
        1833,  369,  825,  729, 1929,  753,  625, 1033,  184, 1513, 1465,
        1449,   25,  905,  192, 1841,  281,  953, 1665, 1321, 1225,   33,
         705,  200,  857,  585,   41,  433,  913, 1689,  208,  457, 1649,
         577,   57,  216, 1145, 1921,  617,  769,  224, 1729, 1713, 1537,
         385,  721,  232, 1913, 1001, 1241,  929,  240, 1681, 1753,  353,
        1497,  248,  313, 1337, 1385,  256,  377,  665, 1897, 1401,  264,
         272, 1129, 1433, 1441,  417,  681,  280,   89, 1905,  288,  296,
         304,  449,  897, 1657,  312,  185,  320,  761, 1473,  328, 1137,
         336,  344, 1577,  352,  817,  360, 1457,  368,  376,  384, 1249,
         473, 1697,  392,  400, 1361,  408,  416,  424,  432,  440,  448,
         456,  464,  472,  480,  488,  496,  504,  512,  520,  528,  536,
         544,  552,  560,  568,  576,  584,  592,  600,  608,  616,  624,
         632,  640,  648,  656,  664,  672,  680,  688,  696,  704,  712,
         720,  728,  736,  744,  752,  760,  768,  776,  784,  792,  800,
         808,  816,  824,  832,  840,  848,  856,  864,  872,  880,  888,
         896,  904,  912,  920,  928,  936,  944,  952,  960,  968,  976,
         984,  992, 1000, 1008, 1016, 1024, 1032, 1040, 1048, 1056, 1064,
        1072, 1080, 1088, 1096, 1104, 1112, 1120, 1128, 1136, 1144, 1152,
        1160, 1168, 1176, 1184, 1192, 1200, 1208, 1216, 1224, 1232, 1240,
        1248, 1256, 1264, 1272, 1280, 1288, 1296, 1304, 1312, 1320, 1328,
        1336, 1344, 1352, 1360, 1368, 1376, 1384, 1392, 1400, 1408, 1416,
        1424, 1432, 1440, 1448, 1456, 1464, 1472, 1480, 1488, 1496, 1504,
        1512, 1520, 1528, 1536, 1544, 1552, 1560, 1568, 1576, 1584, 1592,
        1600, 1608, 1616, 1624, 1632, 1640, 1648, 1656, 1664, 1672, 1680,
        1688, 1696, 1704, 1712, 1720, 1728, 1736, 1744, 1752, 1760, 1768,
        1776, 1784, 1792, 1800, 1808, 1816, 1824, 1832, 1840, 1848, 1856,
        1864, 1872, 1880, 1888, 1896, 1904, 1912, 1920, 1928, 1936, 1944],
       dtype=int64),
 array([502, 403,   1,   1,   1,   3,   1,   1,   2,   1,   1,   1,   9,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1, 252,   2,   1,   2,   1,   1,   1,
          2,   2,   2,   1,   2,   1,   1,   1,  10,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   2,   1,   1,   1,  81,   1,   1,
          2,   1,   1,   1,   1,   1,   1,   1,   2,   1,   2,   2,   1,
          1,   1,   1,   1,   1,   3,   9,   1,   1,   1,   1,   1,   1,
          1,   2,   1,  50,   1,   2,   1,   1,   1,   2,   1,   1,   1,
          1,   1,  16,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   6,   2,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   2,   2,   1,
          1,   1,   2,   2,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   3,   1,   1,   1,   1,
          1,   1,   1,   3,   1,   2,   1,   2,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          2,   1,   1,   1,   2,   2,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,
          1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,
          1,   1,   2,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1], dtype=int64))

In [10]:
np.sum(x[:,4])

93.0

In [11]:
np.mean(x[:,3])#avg of male and female

0.6434426229508197

In [12]:
np.unique(x[:,5])

array([0., 1., 2., 3.])

In [13]:
np.unique(x[:,5],return_counts=True)#for no of days

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

In [14]:
np.sum(x[:,3])

157.0

In [15]:
np.unique(x[:,3])

array([0., 1.])

In [16]:
np.unique(x[:,3],return_counts=True)

(array([0., 1.]), array([ 87, 157], dtype=int64))

In [17]:
tip=x[:,2 ]#avg tip of male and female
sex=x[:,3]
total_tip_male = np.mean(tip[sex == 0])
total_tip_female = np.mean(tip[sex == 1])
print(total_tip_male )
print(total_tip_female )

2.8334482758620685
3.0896178343949043

In [18]:
amount=x[:,1]#  total amount of male and female
sex=x[:,3]
tip=x[:,2]#avg tip of male and female
total_tip_male = np.mean(tip[sex == 0])
total_tip_female = np.mean(tip[sex == 1])
total_amount_male = np.sum(amount[sex == 0])+ np.sum(tip[sex == 0]) #amount spent by male
total_amount_female = np.sum(amount[sex == 1])+ np.sum(tip[sex == 1]) #amount spent by female
print(total_amount_male)
print(total_amount_female)

1817.4599999999996
3741.89

In [25]:
tip=np.min(x[:,2])# min value of tip
tip

1.0

In [32]:
np.max(x[:,2])# max vcalue of tip

10.0

In [40]:
lunch=x[:,6]#how many male and female are going for lunch
sex=x[:,3]
lunch_male = np.sum((sex == 0) & (lunch==0))
lunch_female = np.sum((sex == 1) & (lunch==0))
print('malecount for lunch:',lunch_male)
print('malecount for lunch:',lunch_female)

malecount for lunch: 52
malecount for lunch: 124

In [39]:
dinner=x[:,6]#how many male and female are going for dinner
sex=x[:,3]
dinner_male = np.sum((sex == 0) & (dinner==1))
dinner_female = np.sum((sex == 1) & (dinner==1))
print('malecount for dinner: ',dinner_male)
print('malecount for dinner:',dinner_female)

malecount for dinner:  35
malecount for dinner: 33

In [41]:
np.mean(x[:,7])#avg size

2.569672131147541

In [45]:
#no ofmale and female smokers
smokers=x[:,4]
sex=x[:,3]
male_smokers=np.sum((sex==0)& (smokers == 1))
female_smokers=np.sum((sex==1)& (smokers == 1))
print('male_smokers:',male_smokers)
print('female_smokers:',female_smokers)

male_smokers: 33
female_smokers: 60